CREATE TABLE cart_item (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  item_id integer,
  quantity integer,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar,
  email varchar,
  age integer,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE item (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  price float,
  description text,
  stock integer,
  seller varchar,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE rating (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int,
  item_id int,
  rating float,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int,
  status varchar,
  total float,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE order_item (
  order_id int,
  item_id int,
  price float,
  quantity int
);

ALTER TABLE cart_item ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE cart_item ADD FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE rating ADD FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE rating ADD FOREIGN KEY (item_id) REFERENCES users (id);

ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_item ADD FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_item ADD FOREIGN KEY (item_id) REFERENCES item (id);
