name: Deploy to AWS
on: workflow_dispatch
    # push:
    #   branches: [ "master" ]
    # pull_request:
    #   branches: [ "master" ]  
    # workflow-dispatch:
env:
  AWS_REGION : "us-east-1"

  permissions:
  id-token: write
  contents: read
jobs:
  deployToAws:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./aws
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '18.x'
            cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npx cdk deploy
